import Head from 'next/head';
import AddProject1 from '../src/components/AddProject1';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<AddProject1 />
			</main>
		</div>
	);
}
